@startuml Pile
State Vide
State Utilisée
State Pleine

[*] --> Pleine
Pleine --> Utilisée : Est utilisée
Utilisée --> Vide : Est utilisée [Jusqu'à la fin de la charge] Et non sur la charge

Utilisée --> Pleine : Mise sur la charge [est utilisée]
@enduml