@startuml CanadianTire
title CanadianTire – Modèle du domaine (objets)

object Client {
  nom 
}

object Succursale {
  code
  adresse
}

object Produit {
  Prix
  nom
}

object Inventaire {
  stock
}

object Circulaire {
  titre
  dateDebut
  dateFin
}

Client -- Succursale : possede
Client -- Circulaire : publie

(Succursale, Produit) -- Inventaire : stocke
Circulaire -- Produit : annonce

@enduml