@startuml CanadianTire
title CanadianTire – Modèle du domaine (objets)

object Organisation {
  nom 
}

object Succursale {
  code
  adresse
}

object Produit {
  Prix
  nom
}

object Inventaire {
  stock
}

object Circulaire {
  titre
  dateDebut
  dateFin
}

Organisation -- Succursale : possede
Organisation -- Circulaire : publie

(Succursale, Produit) -- Inventaire : stocke
Circulaire o-- Produit
'composition

@enduml