@startuml CSBuddy
object Membre{
    nom
    alias
    --
    communiquer()
}

object Groupe{
    nom
    alias
}
object Anniversaires{
    date
    --
    célébrer()
}

Groupe o-- "3..*" Membre
Membre -- Membre 
(Membre, Membre) -- Anniversaires



@enduml