@startuml
title Gestion de condos locatifs 
left to right direction

object Personne {
  nom = "Un nom"
}

object Appartement {
  adresse = "123 rue Adresse"
}

object Bail {
  date = "2025-07-01"
  renouveller()
}

(Personne, Appartement) -- Bail

@enduml
