"RentIT, une jeune entreprise œuvrant dans la location de véhicules souhaite informatiser ses opérations en 
créant un système basé sur les technologies web.

Un client peut consulter le site web afin de vérifier l’ensemble des véhicules. Il pourra en effectuer 
la réservation dans la mesure où il accepte de devenir membre ce qui implique de s’enregistrer au système en 
fournissant ses coordonnées, ses informations personnelles incluant la date de naissance ainsi qu’un numéro de 
carte de crédit valide (obligatoire pour les réservations par internet).

Un membre qui désire réserver un véhicule devra avoir 500$ de crédit de libre sur sa carte de crédit, 
montant qui sera débloqué à son retour. Il choisira ensuite une succursale, date et l’heure de prise de
 possession et de retour. RentIT présentera alors la liste des véhicules disponibles (non réservés) selon 
 le groupe d’âge.

Il faut un minimum de 18 ans afin de louer un véhicule compact. Pour les berlines, l’âge passe à 21 ans et à 
25 ans pour les véhicules de luxe.

Quand un client/membre se présente au comptoir pour prendre possession d’un véhicule, il est accueilli 
par un préposé à la location qui s’occupe de préparer le véhicule pour la location. Il notera le km du véhicule,
son niveau d’essence et prendra des photos de l’état initial du véhicule pour enfin procéder au paiement soit en
 argent, par débit (après autorisation de l’institution financière) ou par carte de crédit après confirmation du 
 SAC (système d’autorisation de crédit).



Il effectuera les mêmes opérations lors du retour du véhicule mais pourra, au besoin, réclamer des frais de 
location supplémentaires le cas échéant (dépassement du km, dommages, pleins d’essence non fait).

La liste des véhicules disponible à la location est gérée par le gérant qui œuvre dans l’entreprise au même
 titre qu’un préposé à la location.

Seuls les clients peuvent utiliser le système sans être authentifiés."

@startuml RentIT
left to right direction

actor Client
actor Membre
actor Gérant
actor Préposé

rectangle "Système de location" {
    'Client Space
    usecase "consulter site web" as consult
    usecase "s'enregistrer au système" as subscribe 
    usecase "fournir date de naissance" as birth
    usecase "fournir carte credit" as credit

    'Member Space
    usecase "s'authentifier" as authentify

    'Manager Space
    usecase "gérer liste véhicules" as manage

    'Attendent Space
}

Client --> UC1
Client --> UC3
UC1 --> UC2 : <<include>>

@enduml